services:

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - jerney-network
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      DB_USER: postgres_user
      DB_PASSWORD: postgres_password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    restart: always
    networks:
      - jerney-network
    expose:
      - "5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jerney-network
    healthcheck:
      test: ["CMD", "/usr/bin/pg_isready", "-U", "postgres_user", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  jerney-network:
    driver: bridge

volumes:
  postgres-data:

